<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Serilog.AspNetCore">
        <HintPath>..\..\..\..\..\.nuget\packages\serilog.aspnetcore\9.0.0\lib\net9.0\Serilog.AspNetCore.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
