# Settings and configurations that are common for all containers
services:
  pg_master:
    image: postgres:17
    container_name: pg_master
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env/pg_master.env
    networks:
      - postgres
    volumes:
      - pg_master-storage:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8
    restart: always
    env_file:
      - .env/pg_admin.env
    ports:
      - "8009:80"
    networks:
      - postgres
    volumes:
      - pgadmin-storage:/var/lib/pgadmin
       
networks:
  postgres:
    driver: bridge

volumes:  
  pg_master-storage:
  pgadmin-storage:  